# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/Documents/parallelized-fwi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/Documents/parallelized-fwi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/Documents/parallelized-fwi/CMakeFiles /home/chris/Documents/parallelized-fwi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/Documents/parallelized-fwi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core_library

# Build rule for target.
core_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core_library
.PHONY : core_library

# fast build rule for target.
core_library/fast:
	$(MAKE) -f libraries/core/src/CMakeFiles/core_library.dir/build.make libraries/core/src/CMakeFiles/core_library.dir/build
.PHONY : core_library/fast

#=============================================================================
# Target rules for targets named grid2DTest

# Build rule for target.
grid2DTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid2DTest
.PHONY : grid2DTest

# fast build rule for target.
grid2DTest/fast:
	$(MAKE) -f libraries/core/test/CMakeFiles/grid2DTest.dir/build.make libraries/core/test/CMakeFiles/grid2DTest.dir/build
.PHONY : grid2DTest/fast

#=============================================================================
# Target rules for targets named pressureFieldComplexSerialTest

# Build rule for target.
pressureFieldComplexSerialTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pressureFieldComplexSerialTest
.PHONY : pressureFieldComplexSerialTest

# fast build rule for target.
pressureFieldComplexSerialTest/fast:
	$(MAKE) -f libraries/core/test/CMakeFiles/pressureFieldComplexSerialTest.dir/build.make libraries/core/test/CMakeFiles/pressureFieldComplexSerialTest.dir/build
.PHONY : pressureFieldComplexSerialTest/fast

#=============================================================================
# Target rules for targets named greensSerialTest

# Build rule for target.
greensSerialTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greensSerialTest
.PHONY : greensSerialTest

# fast build rule for target.
greensSerialTest/fast:
	$(MAKE) -f libraries/core/test/CMakeFiles/greensSerialTest.dir/build.make libraries/core/test/CMakeFiles/greensSerialTest.dir/build
.PHONY : greensSerialTest/fast

#=============================================================================
# Target rules for targets named pressureFieldSerialTest

# Build rule for target.
pressureFieldSerialTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pressureFieldSerialTest
.PHONY : pressureFieldSerialTest

# fast build rule for target.
pressureFieldSerialTest/fast:
	$(MAKE) -f libraries/core/test/CMakeFiles/pressureFieldSerialTest.dir/build.make libraries/core/test/CMakeFiles/pressureFieldSerialTest.dir/build
.PHONY : pressureFieldSerialTest/fast

#=============================================================================
# Target rules for targets named sourcesTest

# Build rule for target.
sourcesTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sourcesTest
.PHONY : sourcesTest

# fast build rule for target.
sourcesTest/fast:
	$(MAKE) -f libraries/core/test/CMakeFiles/sourcesTest.dir/build.make libraries/core/test/CMakeFiles/sourcesTest.dir/build
.PHONY : sourcesTest/fast

#=============================================================================
# Target rules for targets named finite_difference_forward_model_library

# Build rule for target.
finite_difference_forward_model_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 finite_difference_forward_model_library
.PHONY : finite_difference_forward_model_library

# fast build rule for target.
finite_difference_forward_model_library/fast:
	$(MAKE) -f libraries/forwardModel/finiteDifference/src/CMakeFiles/finite_difference_forward_model_library.dir/build.make libraries/forwardModel/finiteDifference/src/CMakeFiles/finite_difference_forward_model_library.dir/build
.PHONY : finite_difference_forward_model_library/fast

#=============================================================================
# Target rules for targets named FDTest

# Build rule for target.
FDTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FDTest
.PHONY : FDTest

# fast build rule for target.
FDTest/fast:
	$(MAKE) -f libraries/forwardModel/finiteDifference/test/CMakeFiles/FDTest.dir/build.make libraries/forwardModel/finiteDifference/test/CMakeFiles/FDTest.dir/build
.PHONY : FDTest/fast

#=============================================================================
# Target rules for targets named integral_forward_model_library

# Build rule for target.
integral_forward_model_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integral_forward_model_library
.PHONY : integral_forward_model_library

# fast build rule for target.
integral_forward_model_library/fast:
	$(MAKE) -f libraries/forwardModel/integral/src/CMakeFiles/integral_forward_model_library.dir/build.make libraries/forwardModel/integral/src/CMakeFiles/integral_forward_model_library.dir/build
.PHONY : integral_forward_model_library/fast

#=============================================================================
# Target rules for targets named conjugate_gradient_inversion_library

# Build rule for target.
conjugate_gradient_inversion_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conjugate_gradient_inversion_library
.PHONY : conjugate_gradient_inversion_library

# fast build rule for target.
conjugate_gradient_inversion_library/fast:
	$(MAKE) -f libraries/inversion/conjugateGradientInversion/src/CMakeFiles/conjugate_gradient_inversion_library.dir/build.make libraries/inversion/conjugateGradientInversion/src/CMakeFiles/conjugate_gradient_inversion_library.dir/build
.PHONY : conjugate_gradient_inversion_library/fast

#=============================================================================
# Target rules for targets named random_inversion_library

# Build rule for target.
random_inversion_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 random_inversion_library
.PHONY : random_inversion_library

# fast build rule for target.
random_inversion_library/fast:
	$(MAKE) -f libraries/inversion/randomInversion/src/CMakeFiles/random_inversion_library.dir/build.make libraries/inversion/randomInversion/src/CMakeFiles/random_inversion_library.dir/build
.PHONY : random_inversion_library/fast

#=============================================================================
# Target rules for targets named gradient_descent_inversion_library

# Build rule for target.
gradient_descent_inversion_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gradient_descent_inversion_library
.PHONY : gradient_descent_inversion_library

# fast build rule for target.
gradient_descent_inversion_library/fast:
	$(MAKE) -f libraries/inversion/gradientDescentInversion/src/CMakeFiles/gradient_descent_inversion_library.dir/build.make libraries/inversion/gradientDescentInversion/src/CMakeFiles/gradient_descent_inversion_library.dir/build
.PHONY : gradient_descent_inversion_library/fast

#=============================================================================
# Target rules for targets named evolution_inversion_library

# Build rule for target.
evolution_inversion_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evolution_inversion_library
.PHONY : evolution_inversion_library

# fast build rule for target.
evolution_inversion_library/fast:
	$(MAKE) -f libraries/inversion/evolutionInversion/src/CMakeFiles/evolution_inversion_library.dir/build.make libraries/inversion/evolutionInversion/src/CMakeFiles/evolution_inversion_library.dir/build
.PHONY : evolution_inversion_library/fast

#=============================================================================
# Target rules for targets named factory_library

# Build rule for target.
factory_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factory_library
.PHONY : factory_library

# fast build rule for target.
factory_library/fast:
	$(MAKE) -f libraries/factory/src/CMakeFiles/factory_library.dir/build.make libraries/factory/src/CMakeFiles/factory_library.dir/build
.PHONY : factory_library/fast

#=============================================================================
# Target rules for targets named FWI_PreProcess

# Build rule for target.
FWI_PreProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_PreProcess
.PHONY : FWI_PreProcess

# fast build rule for target.
FWI_PreProcess/fast:
	$(MAKE) -f applications/preProcessing/CMakeFiles/FWI_PreProcess.dir/build.make applications/preProcessing/CMakeFiles/FWI_PreProcess.dir/build
.PHONY : FWI_PreProcess/fast

#=============================================================================
# Target rules for targets named FWI_PreProcess_Finite_Difference

# Build rule for target.
FWI_PreProcess_Finite_Difference: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_PreProcess_Finite_Difference
.PHONY : FWI_PreProcess_Finite_Difference

# fast build rule for target.
FWI_PreProcess_Finite_Difference/fast:
	$(MAKE) -f applications/finiteDifferencePreProcessing/CMakeFiles/FWI_PreProcess_Finite_Difference.dir/build.make applications/finiteDifferencePreProcessing/CMakeFiles/FWI_PreProcess_Finite_Difference.dir/build
.PHONY : FWI_PreProcess_Finite_Difference/fast

#=============================================================================
# Target rules for targets named FWI_Process_Finite_Difference

# Build rule for target.
FWI_Process_Finite_Difference: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_Process_Finite_Difference
.PHONY : FWI_Process_Finite_Difference

# fast build rule for target.
FWI_Process_Finite_Difference/fast:
	$(MAKE) -f applications/finiteDifferenceProcessing/CMakeFiles/FWI_Process_Finite_Difference.dir/build.make applications/finiteDifferenceProcessing/CMakeFiles/FWI_Process_Finite_Difference.dir/build
.PHONY : FWI_Process_Finite_Difference/fast

#=============================================================================
# Target rules for targets named FWI_Process

# Build rule for target.
FWI_Process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_Process
.PHONY : FWI_Process

# fast build rule for target.
FWI_Process/fast:
	$(MAKE) -f applications/processing/CMakeFiles/FWI_Process.dir/build.make applications/processing/CMakeFiles/FWI_Process.dir/build
.PHONY : FWI_Process/fast

#=============================================================================
# Target rules for targets named FWI_Process_Random_Inversion

# Build rule for target.
FWI_Process_Random_Inversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_Process_Random_Inversion
.PHONY : FWI_Process_Random_Inversion

# fast build rule for target.
FWI_Process_Random_Inversion/fast:
	$(MAKE) -f applications/randomInversionProcessing/CMakeFiles/FWI_Process_Random_Inversion.dir/build.make applications/randomInversionProcessing/CMakeFiles/FWI_Process_Random_Inversion.dir/build
.PHONY : FWI_Process_Random_Inversion/fast

#=============================================================================
# Target rules for targets named FWI_UnifiedProcess

# Build rule for target.
FWI_UnifiedProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_UnifiedProcess
.PHONY : FWI_UnifiedProcess

# fast build rule for target.
FWI_UnifiedProcess/fast:
	$(MAKE) -f applications/unifiedProcessing/CMakeFiles/FWI_UnifiedProcess.dir/build.make applications/unifiedProcessing/CMakeFiles/FWI_UnifiedProcess.dir/build
.PHONY : FWI_UnifiedProcess/fast

#=============================================================================
# Target rules for targets named FWI_Process_Gradient_Descent

# Build rule for target.
FWI_Process_Gradient_Descent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FWI_Process_Gradient_Descent
.PHONY : FWI_Process_Gradient_Descent

# fast build rule for target.
FWI_Process_Gradient_Descent/fast:
	$(MAKE) -f applications/gradientDescentProcessing/CMakeFiles/FWI_Process_Gradient_Descent.dir/build.make applications/gradientDescentProcessing/CMakeFiles/FWI_Process_Gradient_Descent.dir/build
.PHONY : FWI_Process_Gradient_Descent/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... test"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... core_library"
	@echo "... grid2DTest"
	@echo "... pressureFieldComplexSerialTest"
	@echo "... greensSerialTest"
	@echo "... pressureFieldSerialTest"
	@echo "... sourcesTest"
	@echo "... finite_difference_forward_model_library"
	@echo "... FDTest"
	@echo "... integral_forward_model_library"
	@echo "... conjugate_gradient_inversion_library"
	@echo "... random_inversion_library"
	@echo "... gradient_descent_inversion_library"
	@echo "... evolution_inversion_library"
	@echo "... factory_library"
	@echo "... FWI_PreProcess"
	@echo "... FWI_PreProcess_Finite_Difference"
	@echo "... FWI_Process_Finite_Difference"
	@echo "... FWI_Process"
	@echo "... FWI_Process_Random_Inversion"
	@echo "... FWI_UnifiedProcess"
	@echo "... FWI_Process_Gradient_Descent"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

