#ifndef CONJUGATEGRADIENTINVERSIONINPUTCARDREADER_H
#define CONJUGATEGRADIENTINVERSIONINPUTCARDREADER_H


class conjugateGradientInversionInputCardReader
{
public:
    conjugateGradientInversionInputCardReader();
};

#endif // CONJUGATEGRADIENTINVERSIONINPUTCARDREADER_H